      FUNCTION E(K,KMAX)
C
C SPECIFICATION OF INITIAL 3-D ENERGY SPECTRUM IN WAVENO SPACE
C
C THIS VERSION CHOSEN TO MATCH MOON LEE'S INITIAL CONDITIONS
C (SEE LEE & REYNOLDS PP. 226-227 AND TABLE 4.1, P.50)
C RUN ON 128**3 GRID
C
      REAL K,KP,KC,K0
C
      DATA K0/1./
      DATA KP/6.87/
      DATA GAMMA/1.037E-3/
C
      KC=KMAX
C
      E=0.0
C
      IF (K.GE.K0.AND.K.LE.KP) THEN
      E=GAMMA*K*K
C
      ELSE IF (K.GT.KP.AND.K.LE.KC) THEN
      E=GAMMA*KP**(11./3.)*K**(-5./3.)
C
      END IF
C
      RETURN
      END
