#! /bin/sh
# /*@@
#   @file    WMPI
#   @date    Sat Sep  4 19:03:19 1999
#   @author  Tom Goodale
#   @desc
#            Stuff for WMPI - a windows MPI implementation
#   @enddesc
#   @version $Header: /mnt/data2/cvs2svn/cvs-repositories/Cactus/lib/make/extras/MPI/WMPI,v 1.3 2003-08-29 15:59:38 tradke Exp $
#   @enddesc
# @@*/

echo '  WMPI selected'

if test -z "$WMPI_DIR" ; then
   echo '  WMPI selected but no WMPI_DIR set.  Unable to proceed.'
   exit 2
fi

MPI_LIBS='cdvlibf cvwmpi'
MPI_LIB_DIRS="`echo $WMPI_DIR\\\lib\\\Console | sed 's:\\\:\\\\\\\\:g'`"
MPI_INC_DIRS="`echo $WMPI_DIR\\\include | sed 's:\\\:\\\\\\\\:g'`"
