#! /bin/bash
#PBS -r n
#PBS -l walltime=@WALLTIME@
#PBS -W group_list=@ALLOCATION@
#PBS -q @QUEUE@
# ppn is ignored; only ppn=1 is valid
#PBS -l nodes=@NODES@:ppn=1
#PBS @('@CHAINED_JOB_ID@' != '' ? '-hold_jid @CHAINED_JOB_ID@' : '')@
#PBS -N @SHORT_SIMULATION_NAME@
#PBS -M @EMAIL@
#PBS -m abe
#PBS -o @RUNDIR@/@SIMULATION_NAME@.out
#PBS -e @RUNDIR@/@SIMULATION_NAME@.err
cd @SOURCEDIR@
@SIMFACTORY@ run @SIMULATION_NAME@ --machine=@MACHINE@ --restart-id=@RESTART_ID@ @FROM_RESTART_COMMAND@
