#!/bin/bash

#SBATCH -J large_nwchem
#SBATCH -o stdout%J
#SBATCH -e stderr%J
#SBATCH -N 1024
#SBATCH -n 49152
#SBATCH -t 10:00:00
#SBATCH -p test2
#SBATCH -A A-ccsc

export PSM2_MQ_RECVREQS_MAX=33554432
export NWCHEM_BASIS_LIBRARY=/scratch/01032/hliu/works/nwchem_blue/nwchem-src-common512/src/basis/libraries/
export NWCHEM_NWPW_LIBRAR=/scratch/01032/hliu/works/nwchem_blue/nwchem-src-common512/src/data/

export TACC_TASKS_PER_NODE=6
ibrun -np 6144 /scratch/01032/hliu/works/nwchem_blue/nwchem-src-common512/bin/LINUX64/nwchem flops.nw.ccsd > job.ccsd.$SLURM_JOB_ID.out

export TACC_TASKS_PER_NODE=24
ibrun -np 24576 /scratch/01032/hliu/works/nwchem_blue/nwchem-src-common512/bin/LINUX64/nwchem flops.nw.t > job.t.$SLURM_JOB_ID.out
